# -*- coding: utf-8 -*-
"""06. Quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qUXEhoSYi8p87sn0iFn1JWZJ6BqN9rZE

# 6. Quiz

## 어느 결혼식장에서 피로연의 식수 인원을 올바르게 예측하지 못하여 버려지는 음식으로 고민이 많다고 합니다. 현재까지 진행된 결혼식에 대한 결혼식 참석 인원과 그 중에서 식사를 하는 인원의 데이터가 제공될 때, 아래 각 문항에 대한 코드를 작성하시오.

주의) 사전 작업으로 아래 코드 셀을 먼저 실행하시오
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## 1) QuizData.csv 파일로부터 데이터를 읽어와서 결혼식 참석 인원(total), 식수 인원(reception)을 각각의 변수로 저장하시오."""

df = pd.read_csv("QuizData.csv")
df.head()

X = df.iloc[:, :-1].values

y = df.iloc[:, -1].values
y.shape

"""## 2) 전체 데이터를 훈련 세트와 테스트 세트로 분리하시오. 이 때 비율은 75 : 25 로 합니다.

(단, random_state = 0 으로 설정)
"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=0)

"""## 3) 훈련 세트를 이용하여 단순 선형 회귀 (Simple Linear Regression) 모델을 생성하시오."""

from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

"""## 4) 데이터 시각화 (훈련 세트) 코드를 작성하시오."""

import matplotlib.pyplot as plt
plt.scatter(X_train, y_train)
plt.plot(X_train, reg.predict(X_train), color = "green")
plt.title("Wedding reception (train)")
plt.xlabel("total")
plt.ylabel("reception")
plt.show()

"""## 5) 데이터 시각화 (테스트 세트) 코드를 작성하시오."""

plt.scatter(X_test, y_test)
plt.plot(X_test, reg.predict(X_test), color = "green")
# reg는 훈련세트로 학습시킨 모델이므로 X_test를 넣든, X_train을 넣든 상관 없다.
# -> 이미 선형 회귀식이 정해져있음.
plt.title("Wedding reception (test)")
plt.xlabel("total")
plt.ylabel("reception")
plt.show()

plt.scatter(X_test, y_test)
plt.plot(X_train, reg.predict(X_train), color = "green")
# X_train인 경우
plt.title("Wedding reception (test)")
plt.xlabel("total")
plt.ylabel("reception")
plt.show()

"""### 하지만 X_train의 range가 X_test의 range보다 크기 때문에 그래프의 xlim, ylim이 달라진다.
### (같은 그림임)
"""

plt.scatter(X_test, y_test)
plt.plot(X_train, reg.predict(X_train), color = "green")
plt.plot(X_test, reg.predict(X_test), color = "red")
plt.title("Wedding reception (test)")
plt.xlabel("total")
plt.ylabel("reception")
plt.show()

"""### 설명을 요약한 plot

## 6) 훈련 세트, 테스트 세트에 대해 각각 모델 평가 점수를 구하시오.
"""

reg.score(X_train, y_train)

reg.score(X_test, y_test)

"""## 7) 결혼식 참석 인원이 300명일 때 예상되는 식수 인원을 구하시오."""

reg.predict([[300]])

x1 = 300
def f(x):
    return reg.coef_ * x + reg.intercept_
f(x1)