# -*- coding: utf-8 -*-
"""basicRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jl6qGTi5WhsMTBLg4goKuPa7o_u5VtH4
"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data/AI_youtube/LinearRegressionData.csv")

df.shape

df.head()

X = df.iloc[:, :-1]
y = df.iloc[:, -1]
print(X, y)

reg = LinearRegression()
reg.fit(X, y)

y_pred = reg.predict(X)
y_pred

plt.scatter(X, y, color = "blue")
plt.plot(X, y_pred, color = "green")
plt.title("Score by hours")
plt.xlabel("hours")
plt.ylabel("score")

print("9시간, 8시간 공부했을 때 예상 점수:", reg.predict([[9], [8]]))

print(reg.coef_, reg.intercept_)