# -*- coding: utf-8 -*-
"""01_Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnilUwEBF26uhB2CbYiNukyx0vFVN38O
"""

import pandas as pd

temp = pd.Series([-20, -10, 10, 20])
temp