# -*- coding: utf-8 -*-
"""02_DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZ7MiaqYhi-dFdin8QizmgZitCJjVrUe
"""

import pandas as pd

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}
data

type(data)

data['이름']

"""## Create DataFrame"""

df = pd.DataFrame(data)
df.head()

df['이름']

df[['이름', '키']] # 변수에 대한 접근을 위한 연산자 [], 리스트 연산자 []

"""## DF index"""

df = pd.DataFrame(data, index = ["1번", "2번", "3번", "4번", "5번", "6번", "7번", "8번"])

# 주의점: 인덱스의 개수와 데이터의 개수가 동일해야 함.

df

"""## DF columns"""

# 원하는 변수만 선택 또는 순서 변경

df = pd.DataFrame(data, columns = ["이름", "학교", "키"])
df.head()

# 변수의 순서 바꿔보기

df = pd.DataFrame(data, columns = ["이름", "키", "학교"])
df.head()