# -*- coding: utf-8 -*-
"""05_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpfRYAd2mfmr72ahMVZPHTWUHxu9wYiZ
"""

import pandas as pd
import numpy as np

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', np.nan, np.nan, 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data, index = ["1번", "2번", "3번", "4번", "5번", "6번", "7번", "8번"])
df.index.name = "지원번호"
df.head(3)

"""# Summarize DF"""

# 계산 가능한 데이터에 대해 column 별 데이터의 갯수, 평균, 표준편차, 최소/최댓값 등의 정보를 출력

df.describe()

df.info()

df.tail(3)

df.values

df.index

df.columns

df.shape

df.dtypes

"""## Summarize Series"""

df['키'].describe()

df['키'].min()

df['키'].nlargest(3)

df.loc[df['키'].nlargest(3).index]

df["SW특기"]

df["SW특기"].count()

df['학교'].unique() # unique한 값들만 가져오기(중복 없애기)

df['학교'].nunique() # unique한 항목 개수