# -*- coding: utf-8 -*-
"""07_Data_Selection(loc).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zth9mGi_orFpcurLeoEonkbbbbPkJrqh
"""

import pandas as pd
import numpy as np

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', np.nan, np.nan, 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data, index = ["1번", "2번", "3번", "4번", "5번", "6번", "7번", "8번"])
df.index.name = "지원번호"

df.loc['1번'] # index에 대해 접근

df.loc['1번', '국어'] # index 1번에 해당하는 데이터의 '국어' 변수의 값

df.loc[['1번', '2번'], '영어']

df.loc[['1번', '2번'], ['영어', '수학']]

df.loc['1번':'5번', '국어':'사회']

# 주의점 : 이 방법으로 슬라이싱을 할 때는 1번부터 5번까지 = 1,2,3,4,5이다.
# (기존 파이썬 문법에서는 1:5 = 1,2,3,4)