# -*- coding: utf-8 -*-
"""10_Missing_Value.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwD4G6CgJUxFmtwzrM7lpksI4T91WT33
"""

import pandas as pd
import numpy as np

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', np.nan, np.nan, 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data, index = ["1번", "2번", "3번", "4번", "5번", "6번", "7번", "8번"])
df.index.name = "지원번호"

df_copy = df.copy(deep = True)

"""## fillna"""

df.fillna('') # call-by-value

df.fillna('없음')

df['학교'] = np.nan
df

df.fillna("(알수없음)", inplace = True)
df

# 데이터 복구
df = df_copy.copy(deep = True)
df

df['SW특기'].fillna('확인 중', inplace = True)
df

"""## dropna"""

df = df_copy.copy(deep = True)
df

df.dropna()

'''
axis : index or columns
데이터를 지울지, 변수를 지울지

how : any or all
any(default) = 데이터 또는 변수 중 하나라도 있으면 삭제
all = 데이터 또는 변수 중 모든 값이 na인 경우 삭제
'''

df.dropna(axis='index', how='any') # 지원번호 4번, 5번 데이터 삭제

df.dropna(axis='columns') # SW특기 변수 삭제

df['학교'] = np.nan
df

df.dropna(axis='columns', how='all')