# -*- coding: utf-8 -*-
"""03_legend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lnYzeW8d3V-s7hpiL_wzl-EO3sM-573
"""

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mp

!wget https://github.com/google/fonts/raw/main/ofl/nanumgothic/NanumGothic-Regular.ttf
!wget https://github.com/google/fonts/raw/main/ofl/nanumgothic/NanumGothic-Bold.ttf
!fc-cache -fv
!rm ~/.cache/matplotlib -rf

font_dirs = './'
font_files = fm.findSystemFonts(fontpaths=font_dirs)
for font_file in font_files:
    fm.fontManager.addfont(font_file)
plt.rc('font', family='NanumGothic')

mp.rcParams['font.size'] = 15
mp.rcParams['axes.unicode_minus'] = False

x = [1, 2, 3]
y = [2, 4, 8]

plt.plot(x, y, label='data')
plt.legend(loc='upper right')

plt.plot(x, y, label='data')
plt.legend(loc=(0.7, 0.8)) # 0~1 사이의 값