# -*- coding: utf-8 -*-
"""05_Save_File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4rgTB-Iq9y3mmvZw4DCXBaJZMm76Ol9
"""

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mp

!wget https://github.com/google/fonts/raw/main/ofl/nanumgothic/NanumGothic-Regular.ttf
!wget https://github.com/google/fonts/raw/main/ofl/nanumgothic/NanumGothic-Bold.ttf
!fc-cache -fv
!rm ~/.cache/matplotlib -rf

font_dirs = './'
font_files = fm.findSystemFonts(fontpaths=font_dirs)
for font_file in font_files:
    fm.fontManager.addfont(font_file)
plt.rc('font', family='NanumGothic')

mp.rcParams['font.size'] = 15
mp.rcParams['axes.unicode_minus'] = False

x = [1, 2, 3, 4, 5]
y = [2, 4, 8, 16, 32]

plt.plot(x, y)

plt.savefig('graph.png')

plt.plot(x, y)

plt.savefig('graph.png', dpi=1000)

plt.figure(dpi=200)
plt.plot(x, y)
plt.savefig('graph.png', dpi=100)

# colab에서는 dpi 200으로 보고, 저장은 100으로 하는 방법