# -*- coding: utf-8 -*-
"""04_save_and_load.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1elw5aXdFOLm31kY22U0Jrv-QKqrZxq1f
"""

import pandas as pd

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data, index = ["1번", "2번", "3번", "4번", "5번", "6번", "7번", "8번"])
df.index.name = "지원번호"
df.head(3)

# save as csv

df.to_csv("score.csv", encoding = "UTF-8-sig")

# index = False -> 지원번호(index) 없이 데이터만 저장

# save as txt

df.to_csv("score.txt", sep = '\t', encoding = "UTF-8")

# save as excel

df.to_excel("score.xlsx")

"""## Open"""

df = pd.read_csv("score.csv")
df.head()

# 특정 데이터 제외

df = pd.read_csv("score.csv", skiprows=1) # 처음부터 지정된 개수 만큼의 row를 건너뜀.
df.head()

df = pd.read_csv("score.csv", skiprows=[1]) # '지정한' 인덱스를 제외
df.head()

df = pd.read_csv("score.csv", skiprows=[1, 3, 5])
df.head()

df = pd.read_csv("score.csv", nrows=4) # 지정된 개수 만큼의 row만 가져옴
df.head()

df = pd.read_csv("score.csv", skiprows=2, nrows=4) # 처음 2개 스킵, 이후 4개의 데이터 가져오기
df.head()

"""## Open txt"""

df = pd.read_csv("score.txt", sep = '\t')
df.head()

# 인덱스를 지정하면서 불러오기

df = pd.read_csv("score.txt", sep = '\t', index_col = "지원번호")
df.head()

df = pd.read_csv("score.txt", sep = '\t')
df.set_index("지원번호", inplace = True) # 인덱스 설정 함수 사용
df.head()

"""## Open excel"""

df = pd.read_excel("score.xlsx")
df.head()

df = pd.read_excel("score.xlsx", index_col = "지원번호")
df.head()