# -*- coding: utf-8 -*-
"""08_Data_Selection(iloc).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwzhQTYxHK-hCsBOYc4fUYAYgSGs-ucB
"""

import pandas as pd
import numpy as np

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', np.nan, np.nan, 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data, index = ["1번", "2번", "3번", "4번", "5번", "6번", "7번", "8번"])
df.index.name = "지원번호"

df.iloc[0]
# = df.loc['1번']

df.iloc[4]

df.iloc[0:5] # 0, 1, 2, 3, 4 (5를 포함하지 않는다. 지원번호가 1부터 시작하기 때문에 5번까지 출력된 것.)

df.iloc[0, 1] # 1행 2열의 데이터.

df.iloc[4, 2]

df.iloc[[0, 1]]

df.iloc[[0, 1], 2] # 처음 두 학생의 키 데이터

df.iloc[[0,1], [3, 4]] # 0, 1 위치의 학생의 3, 4 위치 데이터

df.iloc[0:5, 3:8] # 슬라이싱을 활용한 selection에서는 대괄호를 두 번 사용할 필요 없음