# -*- coding: utf-8 -*-
"""09_Data_Selection(Condition).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-yxVaeUaYkZmJc9JrskJfUC5W31b7kt
"""

import pandas as pd
import numpy as np

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', np.nan, np.nan, 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data, index = ["1번", "2번", "3번", "4번", "5번", "6번", "7번", "8번"])
df.index.name = "지원번호"

df['키'] >= 185 # 학생들의 키가 185 이상인지에 대한 bool

filt = (df['키'] >= 185)
df[filt]

df[~filt]

df.loc[filt, '수학']

df.loc[filt, ['이름', '수학', '과학']]

"""## Various Condition"""

# or operation

df.loc[filt & (df['학교'] == '북산고')]

filt2 = filt & (df['학교'] == '북산고')

df.loc[filt2, ['영어', '수학']]

# and operation

df.loc[ (df['키'] < 170) | (df['키'] > 200)]

"""## str Func"""

filt = df['이름'].str.startswith('송')

filt

filt = df['이름'].str.contains('태')

filt

df[~filt]

langs = ["Python", "Java"]
filt = df['SW특기'].isin(langs)

df[filt]

df.iloc[[0,1,6], :] # 세 명이 나왔어야하지만, Python과 PYTHON이 달라서 필터링 실패

langs = ["python", "java"] # 소문자로 통일
filt = df['SW특기'].str.lower().isin(langs)

df[filt]

filt = df["SW특기"].str.contains('Java')
df['filt']

# Nan에 대한 오류

df["SW특기"].str.contains('Java')

# contains 함수가 Nan에 대해 bool 처리를 하지 못 했다.

df["SW특기"].str.contains('Java', na = False)
# na에 대해서 모두 False로 처리

filt = df["SW특기"].str.contains('Java', na = False)

df[filt]