# -*- coding: utf-8 -*-
"""14_Groupby.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPJ92RwhLK59Uvio9A5S_1TzlYHpbMm2
"""

import pandas as pd
import numpy as np

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', np.nan, np.nan, 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data, index = ["1번", "2번", "3번", "4번", "5번", "6번", "7번", "8번"])
df.index.name = "지원번호"

df_copy = df.copy(deep = True)

df.groupby("학교")

df.groupby("학교").get_group("북산고")

df.groupby("학교").get_group("능남고")

df.groupby("학교").mean(numeric_only=True)

df.groupby('학교').size()

df.groupby("학교")['키'].mean() # 학교로 그룹화를 한 후 키의 평균 데이터를

df.groupby('학교')[['국어', '영어', '수학']].mean()

df['grade'] = [3,3,2,1,1,3,2,2]

df

df.groupby(['학교', 'grade']).mean(numeric_only=True)

df.groupby('grade').mean(numeric_only=True)

df.groupby('grade').mean(numeric_only=True).sort_values('키')

df.groupby('grade').mean(numeric_only=True).sort_values('키', ascending=False)

df.groupby(['학교', 'grade']).sum(numeric_only=True)

df.groupby('학교')[['이름', 'SW특기']].count()

# 북산고에는 SW특기가 Nan인 인원이 2명 있기 때문에
# 이름은 5, SW특기는 3이다.

school = df.groupby('학교')
school['grade'].value_counts()

school['grade'].value_counts().loc['북산고']

school['grade'].value_counts(normalize=True).loc['북산고']