# -*- coding: utf-8 -*-
"""01_Graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqLa_M3h1_LeJkUz40lyh40XBJTzYl9U
"""

import matplotlib.pyplot as plt

x = [1, 2, 3]
y = [2, 4, 8]
print(plt.plot(x, y))

# 함수 반환 값이 출력된다. : [<matplotlib.lines.Line2D at 0x7d7ef0a33f10>]

plt.plot(x, y)
plt.show()

# 반환 값 없이 그래프 출력

plt.plot(x, y)
plt.title("Line Graph")
plt.show()

"""## 한글 폰트 설정"""

import matplotlib.font_manager as fm
# fm.fontManager.ttflist # 사용 가능한 폰트 확인
[f.name for f in fm.fontManager.ttflist]

import matplotlib as mp
mp.rcParams['font.family'] = "AppleGothic"
mp.rcParams['font.size'] = 15
mp.rcParams['axes.unicode_minus'] = False # 한글 폰트 사용 시, 마이너스 글자가 깨지는 현상 해결

plt.plot([-1, 0, 1], [-5, 1, 2])