# -*- coding: utf-8 -*-
"""02_axis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBBf7YUEh_8HmX9IF407ryYSiB21Hxrf
"""

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mp

!wget https://github.com/google/fonts/raw/main/ofl/nanumgothic/NanumGothic-Regular.ttf
!wget https://github.com/google/fonts/raw/main/ofl/nanumgothic/NanumGothic-Bold.ttf
!fc-cache -fv
!rm ~/.cache/matplotlib -rf

font_dirs = './'
font_files = fm.findSystemFonts(fontpaths=font_dirs)
for font_file in font_files:
    fm.fontManager.addfont(font_file)
plt.rc('font', family='NanumGothic')

mp.rcParams['font.size'] = 15
mp.rcParams['axes.unicode_minus'] = False

"""## Details"""

x = [1, 2, 3]
y = [2, 4, 8]
plt.plot(x, y)
plt.title("한글")
plt.xlabel("X축", color = "red")
plt.ylabel("Y축", color = "#00aa00") # rgb
plt.show()

plt.plot(x, y)
plt.title("한글")
plt.xlabel("X축", loc="right") # left, center, right
plt.ylabel("Y축", loc="top") # top, center, bottom
plt.show()

plt.plot(x, y)
# tick 조절
plt.xticks([1, 2, 3])
plt.yticks([3, 6, 9, 12])
plt.show()